package dependencies

object Versions {
    const val gradle = "4.2.2"
    const val compileSdk = 30
    const val minSdk = 21
    const val targetSdk = 30
    const val kotlin = "1.5.21"
    const val kotlin_gradle_plugin = "1.6.0-RC"
    const val ktx = "1.6.0"
    const val dagger = "2.25.4"
    const val nav_components = "2.3.0-alpha06"
    const val material_dialogs = "3.2.1"
    const val room = "2.3.0"
    const val appcompat = "1.3.0"
    const val constraintlayout = "2.1.1"
    const val material_design = "1.4.0"
    const val play_core = "1.7.1"
    const val play_services = "4.3.3"
    const val leak_canary = "2.0-alpha-3"
    const val swipe_refresh_layout = "1.1.0"
    const val firebase_firestore = "21.4.2"
    const val firebase_analytics = "17.4.1"
    const val firebase_crashlytics = "17.0.0"
    const val firebase_auth = "19.3.0"
    const val espresso_core = "3.1.1"
    const val espresso_idling_resource = "3.2.0"
    const val mockk_version = "1.9.2"
    const val test_runner = "1.2.0"
    const val test_core = "1.2.0"
    const val coroutines_version = "1.3.0"
    const val coroutines_play_services = "1.3.2"
    const val lifecycle_version = "2.2.0-alpha03"
    const val retrofit2_version = "2.6.0"
    const val markdown_processor = "0.1.3"
    const val junit_jupiter_version = "5.6.0"
    const val junit_4_version = "4.12"
    const val fragment_version = "1.2.0"
    const val androidx_test_ext = "1.1.1"
    const val crashlytics_gradle = "2.1.0"
}